apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.portal" . }}"
  labels:
{{ include "harbor.portal.labels" . | indent 4 }}
spec:
{{- if  (eq .Values.expose.ingress.controller "gce") }}
  type: NodePort
{{- end }}
  ports:
    - port: {{ template "harbor.portal.servicePort" . }}
      targetPort: {{ template "harbor.portal.containerPort" . }}
  selector:
{{ include "harbor.portal.matchLabels" . | indent 4 }}
