{{- if eq .Values.redis.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.redis" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
{{ include "harbor.redis.labels" . | indent 4 }}
spec:
  ports:
    - port: 6379
  selector:
{{ include "harbor.redis.matchLabels" . | indent 4 }}
{{- end -}}